### ISSUE TITLE
How can I change the name of 'Constance' in the Admin header?

### ISSUE THREAD

**Issue by xpostudio4** [jezdez/django-constance#102]
![screen shot 2015-05-15 at 11 22 25 pm](https://cloud.githubusercontent.com/assets/755375/7664502/2d09b4b6-fb59-11e4-9bde-d9256a8dc4d7.png)

**Comment by jezdez** [comment]
Pretty simply, follow the descriptions here: https://docs.djangoproject.com/en/1.8/ref/applications/#for-application-users Just import `constance.apps.ConstanceConfig` to create your own subclass in your project, then use the dotted path to that subclass in your `INSTALLED_APPS` setting instead of `'constance'`

**Comment by jezdez** [comment]
Oh, you'll want to override the `verbose_name` class attribute of course. Good luck!

**Comment by paulhauner** [comment]
Thanks @jezdez, that was very useful.

Here is a direct example:

```
# project_name/apps.py

from constance.apps import ConstanceConfig

class CustomConstance(ConstanceConfig):
    verbose_name = "Configuration"
```

```
# project_name/settings.py

INSTALLED_APPS = [
    'project_name.apps.CustomConstance',
    # ...
]
```
